# More at https://github.com/Homebrew/homebrew-bundle

# 'brew tap'
tap "homebrew/cask"
tap "homebrew/cask-versions"

# 'brew install --cask'
cask "iterm2" 
brew "node"
brew "wget"
brew "git" 
brew "bash-completion"
brew "bash-git-prompt"
cask "postman"
cask "the-unarchiver"
cask "diffmerge"
cask "caffeine"

# research more about `whalebrew`
# whalebrew "whalebrew/wget"

# Browser stuff
cask "google-chrome"
cask "firefox"

